// <auto-generated />
namespace DWA_Assignment1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangedLaneSwimmerTimefromDateTimetoTimeSpan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedLaneSwimmerTimefromDateTimetoTimeSpan));
        
        string IMigrationMetadata.Id
        {
            get { return "202012261706195_Changed-Lane-SwimmerTime-from-DateTime-to-TimeSpan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
