// <auto-generated />
namespace DWA_Assignment1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedVenueandPoolLengthtoMeet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedVenueandPoolLengthtoMeet));
        
        string IMigrationMetadata.Id
        {
            get { return "202012061951595_Added-Venue-and-PoolLength-to-Meet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
